### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by goodroach** [APDevTeam/StructureBoxes#3]
**Describe the bug**
The console spams you saying "Could not pass CraftTranslateEvent to StructureBoxes"

**To Reproduce**
1. Load Structureboxes as a plugin
2. Make people move around in their ships

**Expected behavior**
No console spam

**Screenshots**
![image](https://user-images.githubusercontent.com/68086172/184465112-c5a15550-4f4b-4f5e-8cd8-b61fe485bc92.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Minecraft version 1.16.5
 - Server software Paper

**Comment by goodroach** [comment]
A potential fix to this is to store a movecraft ship inside of a hashset when piloted (not weak since a player may log off during the time) and remove it once the translate and rotate event goes to pass.

**Comment by TylerS1066** [comment]
I lost track of this, but it seems to have been fixed as we're not seeing it on AP.
